name: Upload TG
on:
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write

jobs:
  Upload_TG:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          name: 'Upload_TG'
          retain_days: 0
          keep_minimum_runs: 0
