name: Merge Upstream
on:
 # schedule:
   # - cron: '30 18 * * 2,5'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: X             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: LSPosed/MagiskOnWSALocal      # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: X          # set the branch to merge to
